android.useAndroidX=true
android.nonTransitiveRClass=true

org.gradle.jvmargs=-Xmx6g -XX:MaxMetaspaceSize=1024m -Dfile.encoding=UTF-8

org.gradle.parallel=true
org.gradle.workers.max=12

org.gradle.configuration-cache=true
org.gradle.configuration-cache.problems=warn
org.gradle.configuration-cache.parallel=true
org.gradle.caching=true

kotlin.daemon.jvmargs=-Xmx3072m
kotlin.incremental.usePreciseJavaTracking=true
kotlin.incremental.cache.ir=true

# Versioning
VERSION_NAME=1.11.0
VERSION_CODE=21
APP_ID=org.pblmotion.calendar
